config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  namespace :api do
    post :upload_image, to: 'utils#upload_image'

    resources :users, only: [] do
      member do
        post :follow
      end
    end

    resources :memos, only: [] do
      member do
        post :clap
	post :clip
      end
    end
  end

  resources :memos do
    resources :comments, only: [:create]
  end

  resources :users, only: [] do
    collection do
      get :pricing
      get :payment
      post :pay
    end
  end

  get '@:username/:memo_id', to: 'pages#show', as: 'memo_page'
  get '@:username', to: 'pages#user', as: 'user_page'
  root 'pages#index'

end

app/views/shared/frontend/_flash.html.erb
<div class="notification is-success is-light">
  <%= notice %>
</div>

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to "My Clone Medium", root_path, class: 'navbar-item has-text-weight-bold' %>
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if user_signed_in? %>
        <div class="navbar-item has-dropdown is-hoverable">
	<a class="navbar-link">
  	  <%= content_tag :i, "", class:'fas fa-crown has-text-primary' if current_user.vip_user? %>
	  <%= content_tag :i, "", class:'fas fa-crown has-text-danger' if current_user.platinum_user? %>
          <%= avatar(current_user, 64) %>
	  <%= current_user.email %>
        </a>

          <div class="navbar-dropdown">
            <%= link_to "新增筆記", new_memo_path, class: 'navbar-item' %>
	    <%= link_to "筆記簿", memos_path, class: 'navbar-item' %>
            <hr class="navbar-divider">
            <%= link_to "編輯會員資料", edit_user_registration_path, class: 'navbar-item' %>
	    <%= link_to "升級方案", pricing_users_path, class: 'navbar-item' unless current_user.paid_user? %>
            <hr class="navbar-divider">
            <%= link_to "登出", destroy_user_session_path, class: 'navbar-item', method: 'delete', data: {confirm: '確定登出?'} %>
	  </div>
        </div>
	  <% else %>
            <%= link_to "註冊", new_user_registration_path, class: 'button is-primary' %>
            <%= link_to "登入", user_session_path, class: "button is-light" %>
	  <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>