config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  namespace :api do
    post :upload_image, to: 'utils#upload_image'

    resources :users, only: [] do
      member do
        post :follow
      end
    end

    resources :memos, only: [] do
      member do
        post :clap
	post :clip
      end
    end
  end

  resources :memos do
    resources :comments, only: [:create]
  end

  resources :users, only: [] do
    collection do
      get :pricing
      get :payment
      post :pay
    end
  end

  get '@:username/:memo_id', to: 'pages#show', as: 'memo_page'
  get '@:username', to: 'pages#user', as: 'user_page'
  root 'pages#index'

end

app/views/pages/_comment.html.erb
<article class="comment">
  <span class="profile">
    <%= image_tag comment.user.avatar.variant(resize: '50x50'), class: 'avatar' if comment.user.avatar.attached? %>
    <span class="username"><%= comment.user.username %></span>
  </span>
  <%= simple_format(comment.content, class: 'content') %>
  <p class="created_at is-size-7 has-text-right"><%= comment.created_at.to_date %></p>
</article>

app/views/pages/_comment_area.html.erb
<section class="comment-editor">
  <% if user_signed_in? %>
    <%= form_with model: comment, url: memo_comments_path(memo), class: 'comment_form', local: false do |form| %>
      <%= form.text_area :content, rows: 5, class: 'textarea is-small' %>
      <%= form.button '送出', class: 'button is-primary is-fullwidth' %>
    <% end %>
  <% else %>
    <%= link_to "登入", new_user_session_path, class: 'button is-primary' %> <%= link_to "註冊", new_user_registration_path, class: 'button is-info' %>
  <% end %>
</section>

app/views/pages/index.html.erb
<div class="container is-fluid">
  <% if user_signed_in? %>
  <% else %>
    <p class="title is-1">Hello World!</p>
    <p class="content is-large">Coming and writing.</p>
    <%= link_to "註冊帳號", new_user_registration_path, class: 'button is-primary' %>
    <hr />
  <% end %>
  <section class="trend">
    <p class="title is-5">TRENDING ON MY MEDIUM</p>
    <div class="wrap">
      <% @memos.each do |memo| %>
      <div class="memo">
        <article class="media">
          <div class="media-content">
            <span class="title is-6"><%= link_to memo.title, memo_page_path(memo.user.username, memo), class: 'has-text-grey' %></span>
            <p class="abstract is-size-7"><%= strip_tags(memo.content).truncate(80) %></p>
            <p class="is-size-7">by <%= link_to memo.user.username, user_page_path(memo.user.username), class: 'has-text-black' %> | @ <%= time_ago_in_words(memo.created_at) %>前</p>
          </div>
          <figure class="media-right">
            <% if memo.cover_image.attached? %>
              <%= image_tag memo.cover_image.variant(resize: '100x100') %>
            <% end %>
          </figure>
        </article>
      </div>
      <% end %>
    </div>
    <hr />
  </section>
  <section>
    <div class="column">
      <article class="media">
        <div class="media-content">
          <span class="heading">Author</span>
          <p class="title is-5">Title</p>
          <span class="is-size-7">Created at</span>
	</div>
        <figure class="media-right">

        </figure>
      </article>
    </div>
  </section>
</div>

app/views/pages/show.html.erb
<section class="columns has-text-centered memo-content">
  <section class="column is-offset-3 is-6">
    <h1 class="title"><%= @memo.title %></h1>

    <span class="profile" data-controller="user">
      <%= image_tag @memo.user.avatar.variant(resize: "50x50"), class: "avatar" if @memo.user.avatar.attached? %> 
      <span class="username"><%= @memo.user.username %></span>
      <%= link_to '#', class: 'follow-button button', data: {action: 'user#follow', user: @memo.user.id, target: 'user.followButton'} do %>
        <%= (user_signed_in? && current_user.follow?(@memo.user))? 'Followed' : 'Follow' %>
      <% end %>
      <%= link_to '#', class: 'clip-button button', data: {action: 'user#clip', slug: @memo.slug} do %>
        <% if user_signed_in? && current_user.clip?(@memo) %>
          <i class="fas fa-bookmark" data-user-target="clip"></i>
        <% else %>
          <i class="far fa-bookmark" data-user-target="clip"></i>
        <% end %>
      <% end %>
    </span>

    <article class="content">
      <%= image_tag @memo.cover_image.variant(resize: '800x600'), class: 'cover_image' if @memo.cover_image.attached? %>
      <p>
      <%= @memo.content.html_safe %>
      </p>
      
      <footer data-controller="memo">
        <%= link_to "#", class: 'clapButton button is-size-6 is-warning is-light', data: { action: 'memo#addClap', slug: @memo.slug} do %>
	<i class="far fa-thumbs-up"></i><span class="clapCount" data-memo-target="clapCount"><%= @memo.clap %></span>
	<% end %>
      </footer>
    </article>
    <hr>
    <section class="comments">
      <h2>留言</h2>

      <%= render "comment_area", memo: @memo, comment: @comment %>

      <section class="comment-list">
        <%= render partial: "comment", collection: @comments %>
      </section>
    </section>
  </section>
</section>