config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  namespace :api do
    post :upload_image, to: 'utils#upload_image'

    resources :users, only: [] do
      member do
        post :follow
      end
    end

    resources :memos, only: [] do
      member do
        post :clap
	post :clip
      end
    end
  end

  resources :memos do
    resources :comments, only: [:create]
  end

  resources :users, only: [] do
    collection do
      get :pricing
      get :payment
      post :pay
    end
  end

  get '@:username/:memo_id', to: 'pages#show', as: 'memo_page'
  get '@:username', to: 'pages#user', as: 'user_page'
  root 'pages#index'

end

app/models/memo.rb
class Memo < ApplicationRecord
  extend FriendlyId
  friendly_id :slug_candidate, use: :slugged

  include AASM

  acts_as_paranoid

  # relation ships
  belongs_to :user
  has_one_attached :cover_image
  has_many :comments
  has_many :clips

  # validations
  validates :title, presence: true

  # scopes
  scope :published_memos, -> {published.with_attached_cover_image.order(created_at: :desc).includes(:user)}

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize(transliterations: :serbian).to_s
  end

  aasm(column: 'status', no_direct_assignment: true) do
    state :draft, initial: true
    state :published

    event :publish do
      transitions from: :draft, to: :published
    end

    event :unpublish do
      transitions from: :published, to: :draft
    end
  end

  private
  def slug_candidate
    [
      :title,
      [:title, SecureRandom.hex[0, 8]]
    ]
  end

end

app/controllers/api/memos_controller.rb
class Api::MemosController < Api::BaseController
  before_action :find_memo

  def clap
    @memo.increment!(:clap)
    render json: {status: @memo.clap}
  end

  def clip
    render json: {status: current_user.clip!(@memo)}
  end

  private

  def find_memo
    @memo = Memo.friendly.find(params[:id])
  end

end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :authenticate_user!
  before_action :find_memo, only: [:edit, :update, :destroy]

  def index
    @memos = current_user.memos.order(created_at: :desc)
  end

  def new
    @memo = current_user.memos.new
  end

  def create
    @memo = current_user.memos.new(memo_params)
    @memo.publish! if params[:publish]

    if @memo.save
      if params[:publish]
        redirect_to memos_path, notice: "筆記成功發布"
      else
        redirect_to edit_memo_path(@memo), notice: "草稿成功儲存"
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @memo.update(memo_params)
      case
      when params[:publish]
        @memo.publish!
	redirect_to memos_path, notice: "筆記成功發表"
      when params[:unpublish]
        @memo.unpublish!
	redirect_to memos_path, notice: "筆記已撤回"
      else
        redirect_to edit_memo_path(@memo), notice: "草稿成功儲存"
      end
    else
      render :edit
    end
  end

  def destroy
    @memo.destroy
    redirect_to memos_path, notice: "筆記成功刪除"
  end

  private
  def find_memo
    @memo = current_user.memos.friendly.find(params[:id])
  end

  def memo_params
    params.require(:memo).permit(:title, :content, :cover_image)
  end

end

app/helpers/memos_helper.rb
module MemosHelper

  def cover_image(memo, width = 240, height = 180)
    image_tag memo.cover_image.variant(resize: "#{width}x#{height}"), class: 'cover_image box' if memo.cover_image.attached?
  end

end

app/views/memos/_content.html.erb
<% content_for :head do %>
  <%= javascript_pack_tag 'editor' %>
<% end %>

<% if memo.errors.any? %>
   <div class="notification is-danger">
    <%= memo.errors.full_messages.to_sentence %>
  </div>
<% end %>


<%= form_for(memo, html: {class: 'memo-editor'}) do |form| %>
  <div class="field">
    <%= form.label :title, "標題" %>
    <%= form.text_field :title, class: 'input' %>
  </div>
  <div class="field">
    <%= form.label :cover_image, "封面圖" %>
    <%= cover_image(memo, 240, 180) %>
    <div class="file">
      <%= form.file_field :cover_image, class: 'button is-link' %>
    </div>
  </div>
  <div class="field">
    <%= form.label :content, "內文" %>
    <%= form.text_area :content, class: 'textarea' %>
  </div>
  <div class="field">
    <% if memo.published? %>
      <%= form.submit "更新", name: 'save_as_draft', class: 'button is-light' %>
    <% else %>
      <%= form.submit "儲存草稿", name: 'save_as_draft', class: 'button is-light' %>
    <% end %>
      <%= form.submit "分享筆記", name: 'publish', class: 'button is-info' if memo.may_publish? %>
      <%= form.submit "撤回筆記", name: 'unpublish', class: 'button is-danger', data: {confirm: "確定撤回?"} if memo.may_unpublish? %>
  </div>
<% end %>

app/views/memos/edit.html.erb
<h1 class="title">修改筆記</h1>

<% if @memo.errors.any? %>
   <ul>
    <% @memo.errors.full_messages.each do |message| %>
    <% end %>
  </ul>
<% end %>

<%= render "content", memo: @memo %>

app/views/memos/index.html.erb
<h1 class="title is-3">筆記簿</h1>
<% @memos.each do |memo| %>
  <div class="content columns">
    <div class="column is-two-thirds">
      <h2 class="title is-4">
        <%= link_to memo.title, edit_memo_path(memo), class: 'has-text-grey-darker' %>
        <%= content_tag :span, "已發布", class: 'tag is-primary is-light' if memo.published? %>
      </h2>
      <p><%= strip_tags(memo.content).truncate(200) %></p>
      <p>最後編輯於：<%= time_ago_in_words(memo.updated_at) %>前
      <%= link_to "編輯", edit_memo_path(memo), class: 'button is-text is-small' %>
      <%= link_to "刪除", memo_path(memo), method: 'delete', class: 'button is-text is-small is-danger', data: {confirm: "確認刪除?"} %> </p>
    </div>
    <div class="column is-one-third">
      <%= cover_image(memo) %>
    </div>
    <hr />
  </div>
<% end %>

app/views/memos/new.html.erb
<h1 class="title">新增筆記</h1>

<% if @memo.errors.any? %>
   <ul>
    <% @memo.errors.full_messages.each do |message| %>
    <% end %>
  </ul>
<% end %>
	
<%= render "content", memo: @memo %>	